name: flutter_game
description: "A cute mobile pixel-art survivor roguelike starring Witch Kitty."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  shared_preferences: ^2.5.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/characters/player_character/color_1/
    - assets/characters/player_character/color_2/
    - assets/characters/enemies/slime_v2/
    - assets/characters/enemies/boss_dino/
    - "assets/bgm/xDeviruchi - Title Theme .wav"
    - "assets/bgm/xDeviruchi - And The Journey Begins .wav"
    - "assets/bgm/xDeviruchi - Exploring The Unknown.wav"
    - "assets/bgm/xDeviruchi - Prepare for Battle! .wav"
    - "assets/bgm/xDeviruchi - Decisive Battle.wav"
    - assets/sfx/Cat_Meow.wav
    - assets/sfx/Sword_Slash.wav
    - assets/sfx/Gun.wav
    - assets/sfx/Explosion.wav
    - assets/sfx/Hurt.wav
    - assets/sfx/Powerup.wav
    - assets/sfx/Confirm.wav
    - assets/sfx/Cancel.wav
    - assets/sfx/Pause.wav
    - assets/sfx/Low_Health.wav
    - assets/sfx/Siren.wav
    - assets/sfx/Monster_Scream.wav
    - assets/orbs/orbs-sheet.png
    - assets/tileset/
    - assets/xp-gem/xp.png
    - "assets/level-up-effect/Level Up Effect Spritesheet.png"
    - assets/orbs/orb-hit-effect/purple/purple-spritesheet.png
    - assets/orbs/fire-orb-projectile/ShotLoop-Sheet.png
    - assets/orbs/fire-orb-projectile/Explode-Sheet.png
    - assets/upgrade-icons/16x16/potion_01a.png
    - assets/upgrade-icons/16x16/boots_01c.png
    - assets/upgrade-icons/16x16/staff_01c.png
    - assets/upgrade-icons/16x16/ring_01d.png
    - assets/upgrade-icons/16x16/crystal_01c.png
    - assets/upgrade-icons/16x16/gem_01j.png
    - assets/upgrade-icons/16x16/pearl_01c.png
  fonts:
    - family: friendlyscribbles
      fonts:
        - asset: assets/font/friendlyscribbles.ttf
